# tools/alarm/alarm_tool.py
# TODO: describe what this connector does in one line.
# Domain: productivity | Mechanism: connector
# Permission: read_only | Response style: verbatim
#
# Scaffold generated by apps/skill_creator/init_skill.py
# Fill in validate() and execute() then set enabled: true in connector.json.

from tools.base_connector import BaseConnector


class AlarmConnector(BaseConnector):
    name = "alarm"
    version = "1.0.0"
    description = "TODO: one sentence used by the intent classifier."
    permission_level = "read_only"

    def validate(self, payload: dict) -> bool:
        # TODO: check required input fields.
        return isinstance(payload, dict)

    def execute(self, payload: dict) -> dict:
        # TODO: implement the actual work.
        # Return {"status": "success", "output": "..."}
        #     or {"status": "error",   "output": "..."}
        raise NotImplementedError(
            f"Implement alarm connector logic, Sir. "
            f"Then set enabled: true in tools/alarm/connector.json."
        )
