# apps/skill_creator/init_skill.py
# Scaffolds a new Aegon skill: connector.json + tool stub + __init__ + test stub.
# All generated skills start with enabled: false (Axiom 4 gate).
# Sir audits the code, fills TODOs, then sets enabled: true in connector.json.
#
# Usage (from project root, venv active):
#   python -m apps.skill_creator.init_skill

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
TOOLS_DIR = PROJECT_ROOT / "tools"
TESTS_DIR = PROJECT_ROOT / "tests"

DOMAINS = [
    "productivity", "communication", "finance", "health",
    "research", "creative", "smart-home", "government", "dev",
]
PERMISSION_LEVELS = ["read_only", "write_gated", "always_gated"]
RESPONSE_STYLES   = ["verbatim", "summarize", "raw", "confirm"]
MECHANISMS        = ["connector", "bundle", "proactive", "mode"]


# ── helpers ──────────────────────────────────────────────────────────────────

def _ask(prompt: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    value = input(f"{prompt}{hint}: ").strip()
    return value or default


def _choose(prompt: str, options: list[str]) -> str:
    print(f"\n{prompt}")
    for i, opt in enumerate(options, 1):
        print(f"  {i}. {opt}")
    while True:
        raw = input("Choice (number or name): ").strip().lower()
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1]
        if raw in options:
            return raw
        print(f"  Enter a number 1–{len(options)} or one of: {', '.join(options)}")


def _to_class_name(snake: str) -> str:
    """reminder → Reminder, smart_home → SmartHome"""
    return "".join(w.capitalize() for w in snake.split("_"))


def _validate_name(name: str) -> str:
    clean = "".join(c if c.isalnum() or c == "_" else "_" for c in name.lower())
    if not clean or not clean[0].isalpha():
        raise ValueError(f"Skill name must start with a letter. Got: {name!r}")
    return clean


# ── template generators ───────────────────────────────────────────────────────

def _connector_json(cfg: dict) -> str:
    doc = {
        "name":             cfg["name"],
        "version":          "1.0.0",
        "description":      cfg["description"],
        "domain":           cfg["domain"],
        "mechanism":        cfg["mechanism"],
        "permission_level": cfg["permission_level"],
        "enabled":          False,
        "response_style":   cfg["response_style"],
        "entry_point":      f"tools.{cfg['name']}.{cfg['name']}_tool.{cfg['class_name']}Connector",
        "input_schema":     {},
    }
    return json.dumps(doc, indent=2)


def _tool_py(cfg: dict) -> str:
    name       = cfg["name"]
    class_name = cfg["class_name"]
    perm       = cfg["permission_level"]
    style      = cfg["response_style"]
    domain     = cfg["domain"]
    mechanism  = cfg["mechanism"]

    bundle_note = ""
    if mechanism == "bundle":
        bundle_note = (
            "\n# BUNDLE: import and call other connectors here, then combine their outputs.\n"
            "# from concurrent.futures import ThreadPoolExecutor\n"
            "# from tools.weather.weather_tool import WeatherConnector\n"
        )
    elif mechanism == "proactive":
        bundle_note = (
            "\n# PROACTIVE: this skill watches state and speaks unprompted.\n"
            "# Wire a scheduler (apps/morning_trigger.py pattern) to call execute() on a schedule.\n"
        )

    return f"""\
# tools/{name}/{name}_tool.py
# TODO: describe what this connector does in one line.
# Domain: {domain} | Mechanism: {mechanism}
# Permission: {perm} | Response style: {style}
#
# Scaffold generated by apps/skill_creator/init_skill.py
# Fill in validate() and execute() then set enabled: true in connector.json.
{bundle_note}
from tools.base_connector import BaseConnector


class {class_name}Connector(BaseConnector):
    name = "{name}"
    version = "1.0.0"
    description = "TODO: one sentence used by the intent classifier."
    permission_level = "{perm}"

    def validate(self, payload: dict) -> bool:
        # TODO: check required input fields.
        return isinstance(payload, dict)

    def execute(self, payload: dict) -> dict:
        # TODO: implement the actual work.
        # Return {{"status": "success", "output": "..."}}
        #     or {{"status": "error",   "output": "..."}}
        raise NotImplementedError(
            f"Implement {name} connector logic, Sir. "
            f"Then set enabled: true in tools/{name}/connector.json."
        )
"""


def _init_py(cfg: dict) -> str:
    return f"# tools/{cfg['name']}/ — {cfg['description']}\n"


def _test_stub(cfg: dict) -> str:
    name       = cfg["name"]
    class_name = cfg["class_name"]
    return f"""\
# tests/test_{name}.py
# Isolation + stub tests for the {name} connector.
# Run: python -m tests.test_{name}
#
# Isolation smoke test (before enabling):
#   python -c "from tools.{name}.{name}_tool import {class_name}Connector; \\
#              print({class_name}Connector().execute({{}}))"
#
# Full-chain test (after enabling):
#   Run the orchestrator and ask a natural-language trigger, e.g.:
#   "TODO: describe the trigger phrase here"

from tools.{name}.{name}_tool import {class_name}Connector


def test_validate_accepts_empty_dict():
    assert {class_name}Connector().validate({{}}) is True


def test_execute_raises_until_implemented():
    try:
        {class_name}Connector().execute({{}})
        assert False, "Should have raised NotImplementedError"
    except NotImplementedError:
        pass  # expected — fill in execute() first


if __name__ == "__main__":
    test_validate_accepts_empty_dict()
    test_execute_raises_until_implemented()
    print("Stub tests pass. Implement the connector then re-run, Sir.")
"""


# ── main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    print("=" * 60)
    print("Aegon Skill Creator — scaffold a new skill")
    print("=" * 60)

    raw_name = _ask("\nSkill name (snake_case, e.g. 'reminder' or 'smart_home')")
    try:
        name = _validate_name(raw_name)
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)

    if (TOOLS_DIR / name).exists():
        print(f"Error: tools/{name}/ already exists. Choose a different name.")
        sys.exit(1)

    description = _ask(
        "One-sentence description (the intent classifier reads this)",
        default=f"TODO: describe {name}",
    )
    domain    = _choose("Domain", DOMAINS)
    mechanism = _choose("Mechanism", MECHANISMS)
    perm      = _choose("Permission level", PERMISSION_LEVELS)
    style     = _choose("Response style", RESPONSE_STYLES)

    cfg = {
        "name":             name,
        "class_name":       _to_class_name(name),
        "description":      description,
        "domain":           domain,
        "mechanism":        mechanism,
        "permission_level": perm,
        "response_style":   style,
    }

    skill_dir = TOOLS_DIR / name
    skill_dir.mkdir(parents=True)

    (skill_dir / "connector.json").write_text(_connector_json(cfg), encoding="utf-8")
    (skill_dir / f"{name}_tool.py").write_text(_tool_py(cfg), encoding="utf-8")
    (skill_dir / "__init__.py").write_text(_init_py(cfg), encoding="utf-8")
    (TESTS_DIR / f"test_{name}.py").write_text(_test_stub(cfg), encoding="utf-8")

    print(f"\n{'=' * 60}")
    print(f"Skill '{name}' scaffolded:")
    print(f"  tools/{name}/connector.json    (enabled: false — DO NOT change yet)")
    print(f"  tools/{name}/{name}_tool.py    (fill in validate() and execute())")
    print(f"  tools/{name}/__init__.py")
    print(f"  tests/test_{name}.py           (stub tests)")
    print(f"\nNext steps:")
    print(f"  1. Implement tools/{name}/{name}_tool.py")
    print(f"  2. Run: python -m tests.test_{name}")
    print(f"  3. Audit the code, Sir.")
    print(f"  4. Set enabled: true in tools/{name}/connector.json")
    print(f"  5. Full-chain test via the orchestrator.")
    print("=" * 60)


if __name__ == "__main__":
    main()
